services:
  riot-app:
    build:
      context: .
      dockerfile: Dockerfile-riot
    ports:
      - "8000:80"
    volumes:
      - fantasy_sqlitedb:/app/database
      - fantasy_logs:/app/logs

  fantasy-app:
    build:
      context: .
      dockerfile: Dockerfile-fantasy
    ports:
      - "8002:80"
    volumes:
      - fantasy_sqlitedb:/app/database
      - fantasy_logs:/app/logs

volumes:
  fantasy_sqlitedb:
  fantasy_logs: