version: '3'

services:
  fantasylol-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - fantasy_sqlitedb:/app/database
      - fantasy_logs:/app/logs

volumes:
  fantasy_sqlitedb:
  fantasy_logs: