services:
  riot-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile-riot
    ports:
      - "8000:8000"
    volumes:
      - fantasy_sqlitedb:/app/database
      - fantasy_logs:/app/logs

  fantasy-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile-fantasy
    ports:
      - "8002:8002"
    volumes:
      - fantasy_sqlitedb:/app/database
      - fantasy_logs:/app/logs

volumes:
  fantasy_sqlitedb:
  fantasy_logs: