FROM python:3.12-alpine

WORKDIR /app

COPY ../requirements-base.txt /app/requirements-base.txt

RUN pip install --no-cache-dir -r requirements-base.txt

COPY ../src /app/src
COPY ../.env /app

ENV PYTHONPATH="/app/src"

CMD ["python", "-m", "riot_scraper.app"]