FROM python:3.12-alpine

WORKDIR /app

COPY ../pyproject.toml /app/pyproject.toml
COPY ../src /app/src

RUN pip install --no-cache-dir .

ENV PYTHONPATH="/app/src"

CMD ["python", "-m", "riot_scraper.app"]