name: FantasyLoL Pipeline

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint Python Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-base.txt
          pip install -r requirements-dev.txt

      - name: Check code formatting
        run: |
          python -m flake8

      - name: Check typing in src
        run: |
          python -m mypy src

      - name: Check typing in tests
        run: |
          python -m mypy tests

  test:
    name: Run Python tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-base.txt

      - name: Run Tests
        run: |
          python -m unittest discover -s tests -p "test*.py"