name: FantasyLoL Pipeline

on:
  push:
  pull_request:

jobs:
  setup:
    name: Setup & install dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  lint:
    name: Lint Python Code
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Check code formatting
        run: |
          python -m flake8

      - name: Verify Linting Results
        run: |
          if [ $? -eq 0 ]; then
              echo "Linting passed!"
          else
              echo "Linting failed. Fix the issues before pushing or merging"
              exit 1
          fi

  test:
    name: Run Python tests
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Run unittest
        run: |
          python -m unittest discover -s tests -p "test*.py"